# This is a basic workflow to help you get started with Actions

name: vcpkg

on:
  push:


jobs:
          
  macos-env:
    runs-on: macos-latest
    
    steps:
    
      - uses: actions/checkout@v2

      
      - name: Install conda cpp package
        run: |
          sudo ${CONDA}/bin/conda create --yes -p ${HOME}/conda_envs/cpp_pkgs -c conda-forge python=3.9 boost-cpp eigen nlohmann_json mkl mkl-devel mkl-include catch2 
          
      - name: show
        run: |
          export MKL_INCLUDE=${HOME}/conda_envs/cpp_pkgs/include
          export MKL_LIB=${HOME}/conda_envs/cpp_pkgs/include
          echo ${MKL_INCLUDE}
          ls ${MKL_INCLUDE}
          cat ${MKL_INCLUDE}/mkl.h
