# This is a basic workflow to help you get started with Actions

name: vcpkg

on:
  push:


jobs:
          
  macos-env:
    runs-on: macos-latest
    
    steps:
    
      - uses: actions/checkout@v2

      - name: Cache conda cpp package
        uses: actions/cache@v2
        id: cache
        env:
          cache-name: conda-envs-macos
        with:
          path: ${HOME}/conda_envs/cpp_pkgs
          key: conda-envs-macos-1
      
      - name: Install conda cpp package
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          sudo ${CONDA}/bin/conda create --yes -p ${HOME}/conda_envs/cpp_pkgs -c conda-forge python=3.9 boost-cpp eigen nlohmann_json mkl mkl-devel mkl-include catch2 
          
      - name: show
        run: |
          echo ${HOME}
          ls ${HOME}/conda_envs/cpp_pkgs/include
          cat ${HOME}/conda_envs/cpp_pkgs/include/mkl.h
