# This is a basic workflow to help you get started with Actions

name: vcpkg

on:
  push:


jobs:
  prepare-env:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: cache conda envs
        uses: actions/cache@v2
        id: cache
        env:
          cache-name: conda-envs-windows
        with:
          path: C:\conda_envs
          key: conda-envs-windows-2
      
      # Runs a set of commands using the runners shell
      - name: activate conda environments
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          C:\Miniconda\condabin\conda init
      - name: prepare conda environments
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          conda create --yes -p C:\conda_envs\cpp_pkgs -c conda-forge python=3.9
          conda activate C:\conda_envs\cpp_pkgs
          conda install --yes -c conda-forge boost-cpp eigen nlohmann_json mkl mkl-devel mkl-include catch2

          conda create --yes -p C:\conda_envs\cp37-cp37m -c conda-forge python=3.7
          conda activate C:\conda_envs\cp37-cp37m
          pip install --no-cache-dir -r dev-requirements.txt

          conda create --yes -p C:\conda_envs\cp38-cp38 -c conda-forge python=3.8
          conda activate C:\conda_envs\cp38-cp38
          pip install --no-cache-dir -r dev-requirements.txt

          conda create --yes -p C:\conda_envs\cp39-cp39 -c conda-forge python=3.9
          conda activate C:\conda_envs\cp39-cp39
          pip install --no-cache-dir -r dev-requirements.txt
          
          conda clean --yes --all
  
  show-env:
    runs-on: windows-latest
    needs: prepare-env
    strategy:
      matrix:
        python-version: [cp37-cp37m, cp38-cp38, cp39-cp39]
    
    steps:
      - uses: actions/checkout@v2
      
      - name: cache conda envs
        uses: actions/cache@v2
        id: cache
        env:
          cache-name: conda-envs-windows
        with:
          path: C:\conda_envs
          key: conda-envs-windows-2
        
      - name: check cache
        if: steps.cache.outputs.cache-hit != 'true'
        run: throw "cache not found!"
      
      - name: activate conda environments
        run: |
          C:\Miniconda\condabin\conda init
      
      - name: show conda list
        run: |
          conda activate C:\conda_envs\${{ matrix.python-version }}
          conda list
          
  macos-env:
    runs-on: macos-latest
    
    steps:
      - name: activate conda environments
        run: |
          ${CONDA}/conda init
      
      - name: install conda cpp package
        run: |
          conda create --yes -p /conda_envs/cpp_pkgs -c conda-forge python=3.9 conda-forge boost-cpp eigen nlohmann_json mkl mkl-devel mkl-include catch2 
